apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: eksa-01
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-11
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 10.4.32.25
    machineGroupRef:
      kind: VSphereMachineConfig
      name: eksa-01-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: eksa-01
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: eksa-01-etcd
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  kubernetesVersion: "1.21"
  managementCluster:
    name: eksa-01
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: eksa-01-ng
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: eksa-01
  namespace: default
spec:
  datacenter: SDDC-Datacenter
  insecure: false
  network: /SDDC-Datacenter/network/eks-workload-network
  server: vcenter.sddc-18-211-251-188.vmwarevmc.com
  thumbprint: AA:17:79:A0:E0:E3:49:11:3F:30:EF:89:39:1B:B7:B6:94:CC:0F:6A

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: eksa-01-cp
  namespace: default
spec:
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/SDDC-Datacenter/vm/vibhutig
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/ubuntu-v1.21.13-kubernetes-1-21-eks-15-amd64-8cecfcd
  users:
  - name: capv
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBrPxf0qCkuBPn3VDeZgv6nc0YfCXiH4WVhE8oVCgoEoxZeAkiTJoxol6p0iWWagv+KoeZJrsxUraqV/faIaLvwlmCcLuIa9A5q2pN6NhgKPmFzcm25EngyelFmqwB8FUh7nx8Jo28urdoSYCxzVAaG6uBa6wtui4cm8ihwKV2CG9e+ihk+iqrnwD28LwnAYn54TgjxzvW8H4QXugXZb8EEmhKV9SlA0emngp0J+gAb8aO/hfbq4TlHjO7HpSG2ZWY9+NYx8DCn02Th6hBflEqH89T0meR/PILCQ3TF/hkcF9LP/UjU7vlyDjnZRQCl3lE9Usc45GmJy01IlM+aNqxL0QS1igoE5Ng2KvhXL/Yf/gikFRbgwwnTz14+4mLBoQGAIdze98LXYPfGwp2fJ4yqv5zuGlyzXDv6gS1yv9vPEP1mBItO/pC2r5j7SQUVhB2+Yp/QLnkxv9smnjohY4I9ZnY9CiDFJl10T91D8/4f2lTCAE9s8Uf9uKebAQYT044+BnPvChslj3rpupMLveVcYImLqvoUjSVuEYd60It98iigJWpUh1N5ihZ7Zryp55YJDu6nUL3qvn4ugxSj9RiMX+hyBJkib4U8s/Bxjp9IwSyzsrkvDdttevIaXoM53rCN0XfV71HQZHdx7Jnlm06JwvWXBlhMPd9mn8zHSRcsw==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: eksa-01-etcd
  namespace: default
spec:
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/SDDC-Datacenter/vm/vibhutig
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/ubuntu-v1.21.13-kubernetes-1-21-eks-15-amd64-8cecfcd
  users:
  - name: capv
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBrPxf0qCkuBPn3VDeZgv6nc0YfCXiH4WVhE8oVCgoEoxZeAkiTJoxol6p0iWWagv+KoeZJrsxUraqV/faIaLvwlmCcLuIa9A5q2pN6NhgKPmFzcm25EngyelFmqwB8FUh7nx8Jo28urdoSYCxzVAaG6uBa6wtui4cm8ihwKV2CG9e+ihk+iqrnwD28LwnAYn54TgjxzvW8H4QXugXZb8EEmhKV9SlA0emngp0J+gAb8aO/hfbq4TlHjO7HpSG2ZWY9+NYx8DCn02Th6hBflEqH89T0meR/PILCQ3TF/hkcF9LP/UjU7vlyDjnZRQCl3lE9Usc45GmJy01IlM+aNqxL0QS1igoE5Ng2KvhXL/Yf/gikFRbgwwnTz14+4mLBoQGAIdze98LXYPfGwp2fJ4yqv5zuGlyzXDv6gS1yv9vPEP1mBItO/pC2r5j7SQUVhB2+Yp/QLnkxv9smnjohY4I9ZnY9CiDFJl10T91D8/4f2lTCAE9s8Uf9uKebAQYT044+BnPvChslj3rpupMLveVcYImLqvoUjSVuEYd60It98iigJWpUh1N5ihZ7Zryp55YJDu6nUL3qvn4ugxSj9RiMX+hyBJkib4U8s/Bxjp9IwSyzsrkvDdttevIaXoM53rCN0XfV71HQZHdx7Jnlm06JwvWXBlhMPd9mn8zHSRcsw==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: eksa-01-ng
  namespace: default
spec:
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/SDDC-Datacenter/vm/vibhutig
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/ubuntu-v1.21.13-kubernetes-1-21-eks-15-amd64-8cecfcd
  users:
  - name: capv
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBrPxf0qCkuBPn3VDeZgv6nc0YfCXiH4WVhE8oVCgoEoxZeAkiTJoxol6p0iWWagv+KoeZJrsxUraqV/faIaLvwlmCcLuIa9A5q2pN6NhgKPmFzcm25EngyelFmqwB8FUh7nx8Jo28urdoSYCxzVAaG6uBa6wtui4cm8ihwKV2CG9e+ihk+iqrnwD28LwnAYn54TgjxzvW8H4QXugXZb8EEmhKV9SlA0emngp0J+gAb8aO/hfbq4TlHjO7HpSG2ZWY9+NYx8DCn02Th6hBflEqH89T0meR/PILCQ3TF/hkcF9LP/UjU7vlyDjnZRQCl3lE9Usc45GmJy01IlM+aNqxL0QS1igoE5Ng2KvhXL/Yf/gikFRbgwwnTz14+4mLBoQGAIdze98LXYPfGwp2fJ4yqv5zuGlyzXDv6gS1yv9vPEP1mBItO/pC2r5j7SQUVhB2+Yp/QLnkxv9smnjohY4I9ZnY9CiDFJl10T91D8/4f2lTCAE9s8Uf9uKebAQYT044+BnPvChslj3rpupMLveVcYImLqvoUjSVuEYd60It98iigJWpUh1N5ihZ7Zryp55YJDu6nUL3qvn4ugxSj9RiMX+hyBJkib4U8s/Bxjp9IwSyzsrkvDdttevIaXoM53rCN0XfV71HQZHdx7Jnlm06JwvWXBlhMPd9mn8zHSRcsw==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-01
  github:
    owner: 22vibhutigoel
    personal: true
    repository: eksa
  systemNamespace: flux-system

---
