apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: workload
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-38
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 10.4.131.206
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: workload
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload-etcd
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  identityProviderRefs:
  - kind: AWSIamConfig
    name: aws-iam-auth-config
  kubernetesVersion: "1.26"
  managementCluster: {}
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: workload
  namespace: default
spec:
  datacenter: SDDC-Datacenter
  insecure: false
  network: /SDDC-Datacenter/network/eks-workload-network
  server: vcenter.sddc-18-211-251-188.vmwarevmc.com
  thumbprint: AA:17:79:A0:E0:E3:49:11:3F:30:EF:89:39:1B:B7:B6:94:CC:0F:6A

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: workload-cp
  namespace: default
spec:
  cloneMode: fullClone
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/SDDC-Datacenter/vm/eksa-demo-vibhutig
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/bottlerocket-v1.26.4-kubernetes-1-26-eks-9-amd64-0ae702d
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDq5BEA/BDgwLh83Vz6OPj9ZhlEsWnE6nIs6FfgHKLrQeBtts5lknrBo/q8u32P+SIphcwEFv3a5Rp0oVIsvuwUly+QAu3z+myghnW+n73aAhaZLn/sdDbTorbu0zLjfqrY2KXMnBRyyCo6R7Pu1JQNnN49aL2LSRxWPTHeD5jpiSpT6M73lspLTuQsuYeIg3eDHJL7Umm0kBQCIYl+8o0mxytBywuSGAHmkRJkNwDwedtibc5hdqz9eatiqd/7tgulVr47HIa5705XW6pWab16UeM9mm7rP12gwkfAdpkbW2enPRUbUAgwvQJuB3oXjAVQm14WK22VghebhJElZcXLH0WJ1x2PN8pHeNvrand5Fx9Kg1k1AlQ8lz13E6BXVHkOOcToi0vdda+DdlB4ECg4PCpe1nZ4qjEhL9WbwTmMehz1yayUYZ+Wx2QqVSmutOPwd99NVnzHogdAlE5TkIAfN4/NN02vUzFdN0uhy0lz8v0v9AF0aI43TKunUhQlq2ww7cmZMbJ0Iwcb3wxxHZPuRSk2nDHGIvRK9XDYvgkVICZGBNrNV06i1+t9BwhiNLrwSHTBw5LsJiLl3T/FY4HK6hUkEPle5rVAShcfnmUYNv1oY2EAd4naMsS7h5NriVBXKFAkpN1V4TqYMZlS6gyxWx0FGZKpfp0CQud5Vvc4BQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: workload
  namespace: default
spec:
  cloneMode: fullClone
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/SDDC-Datacenter/vm/eksa-demo-vibhutig
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/bottlerocket-v1.26.4-kubernetes-1-26-eks-9-amd64-0ae702d
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDq5BEA/BDgwLh83Vz6OPj9ZhlEsWnE6nIs6FfgHKLrQeBtts5lknrBo/q8u32P+SIphcwEFv3a5Rp0oVIsvuwUly+QAu3z+myghnW+n73aAhaZLn/sdDbTorbu0zLjfqrY2KXMnBRyyCo6R7Pu1JQNnN49aL2LSRxWPTHeD5jpiSpT6M73lspLTuQsuYeIg3eDHJL7Umm0kBQCIYl+8o0mxytBywuSGAHmkRJkNwDwedtibc5hdqz9eatiqd/7tgulVr47HIa5705XW6pWab16UeM9mm7rP12gwkfAdpkbW2enPRUbUAgwvQJuB3oXjAVQm14WK22VghebhJElZcXLH0WJ1x2PN8pHeNvrand5Fx9Kg1k1AlQ8lz13E6BXVHkOOcToi0vdda+DdlB4ECg4PCpe1nZ4qjEhL9WbwTmMehz1yayUYZ+Wx2QqVSmutOPwd99NVnzHogdAlE5TkIAfN4/NN02vUzFdN0uhy0lz8v0v9AF0aI43TKunUhQlq2ww7cmZMbJ0Iwcb3wxxHZPuRSk2nDHGIvRK9XDYvgkVICZGBNrNV06i1+t9BwhiNLrwSHTBw5LsJiLl3T/FY4HK6hUkEPle5rVAShcfnmUYNv1oY2EAd4naMsS7h5NriVBXKFAkpN1V4TqYMZlS6gyxWx0FGZKpfp0CQud5Vvc4BQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: workload-etcd
  namespace: default
spec:
  cloneMode: fullClone
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/SDDC-Datacenter/vm/eksa-demo-vibhutig
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/bottlerocket-v1.26.4-kubernetes-1-26-eks-9-amd64-0ae702d
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDq5BEA/BDgwLh83Vz6OPj9ZhlEsWnE6nIs6FfgHKLrQeBtts5lknrBo/q8u32P+SIphcwEFv3a5Rp0oVIsvuwUly+QAu3z+myghnW+n73aAhaZLn/sdDbTorbu0zLjfqrY2KXMnBRyyCo6R7Pu1JQNnN49aL2LSRxWPTHeD5jpiSpT6M73lspLTuQsuYeIg3eDHJL7Umm0kBQCIYl+8o0mxytBywuSGAHmkRJkNwDwedtibc5hdqz9eatiqd/7tgulVr47HIa5705XW6pWab16UeM9mm7rP12gwkfAdpkbW2enPRUbUAgwvQJuB3oXjAVQm14WK22VghebhJElZcXLH0WJ1x2PN8pHeNvrand5Fx9Kg1k1AlQ8lz13E6BXVHkOOcToi0vdda+DdlB4ECg4PCpe1nZ4qjEhL9WbwTmMehz1yayUYZ+Wx2QqVSmutOPwd99NVnzHogdAlE5TkIAfN4/NN02vUzFdN0uhy0lz8v0v9AF0aI43TKunUhQlq2ww7cmZMbJ0Iwcb3wxxHZPuRSk2nDHGIvRK9XDYvgkVICZGBNrNV06i1+t9BwhiNLrwSHTBw5LsJiLl3T/FY4HK6hUkEPle5rVAShcfnmUYNv1oY2EAd4naMsS7h5NriVBXKFAkpN1V4TqYMZlS6gyxWx0FGZKpfp0CQud5Vvc4BQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-demo
  github:
    owner: 22vibhutigoel
    personal: true
    repository: eksa
  systemNamespace: default

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: AWSIamConfig
metadata:
  name: aws-iam-auth-config
  namespace: default
spec:
  awsRegion: us-west-1
  backendMode:
  - EKSConfigMap
  mapRoles:
  - groups:
    - system:masters
    roleARN: arn:aws:iam::880926402103:role/custom-OIDC-eksa-forLogging
    username: eksa-role
  mapUsers:
  - groups:
    - system:masters
    userARN: arn:aws:iam::880926402103:user/eksa-test
    username: eksa-test
  partition: aws

---
