apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: poc-workload
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-40
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 10.4.16.133
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: workload
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload-etcd
  gitOpsRef:
    kind: FluxConfig
    name: my-github-flux-provider
  identityProviderRefs:
  - kind: AWSIamConfig
    name: aws-iam-auth-config
  kubernetesVersion: "1.26"
  managementCluster: {}
  podIamConfig:
    serviceAccountIssuer: https://s3.amazonaws.com/oidc-test-zdvieuchnmbpxnknqimcsceyopiysbrl
  workerNodeGroupConfigurations:
  - autoscalingConfiguration:
      maxCount: 5
      minCount: 3
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: workload
  namespace: default
spec:
  datacenter: SDDC-Datacenter
  insecure: false
  network: /SDDC-Datacenter/network/eks-workload-network
  server: vcenter.sddc-18-211-251-188.vmwarevmc.com
  thumbprint: AA:17:79:A0:E0:E3:49:11:3F:30:EF:89:39:1B:B7:B6:94:CC:0F:6A

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: workload-etcd
  namespace: default
spec:
  cloneMode: fullClone
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/SDDC-Datacenter/vm/EKSAPOC-IND-TML
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/bottlerocket-v1.26.4-kubernetes-1-26-eks-10-amd64-a195374
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0DtKDP/zEo0PS9lURD8K/EXrblDji4lb/Dh6J6GEsLHs3eNTMp1NTA9+dPZIdUHv+UpFK9m3WdjWROgX81KDGsKktLwI1l9Q+01NsGFYSypsLE1T4YZWXMvWBqOIkRmG0dYCyr2DCQ7dexmJ0f7rXZt1EH9UgFelbevVxABXkixt1VAEN3IQGiPx8eXBFzjQRXQG5XoILUlLPNxmCzc1E5pNyAep50Onq5BNwqf0X1i9WPqeLy1ipOKUsO6SO35MAkaN1PoghCNy4JGtqbp1e1wMkUifEwmAP9RIrStJdGj2YaHElQNwhiLDxjpmEh2COkQ1RnERiWpwfJXu0sW038/7lxL6RNQVXf9ZJxF02pbJKGpaL2gvPDQeLkdGMkArDR2Zuc1TIHVx/PrkCpehIm5nawMIzJ83Kug5p+TSnLG4Jx1Vzb9TW8paSn1hZacoV2sVhBvirDW6X6v0TbTyHLylpR1oHTwGdloxxBk3xezV0XpwyjIpFs0CZdsixcus=
      eksademo@eksa-admin

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: workload-cp
  namespace: default
spec:
  cloneMode: fullClone
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/SDDC-Datacenter/vm/EKSAPOC-IND-TML
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/bottlerocket-v1.26.4-kubernetes-1-26-eks-10-amd64-a195374
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0DtKDP/zEo0PS9lURD8K/EXrblDji4lb/Dh6J6GEsLHs3eNTMp1NTA9+dPZIdUHv+UpFK9m3WdjWROgX81KDGsKktLwI1l9Q+01NsGFYSypsLE1T4YZWXMvWBqOIkRmG0dYCyr2DCQ7dexmJ0f7rXZt1EH9UgFelbevVxABXkixt1VAEN3IQGiPx8eXBFzjQRXQG5XoILUlLPNxmCzc1E5pNyAep50Onq5BNwqf0X1i9WPqeLy1ipOKUsO6SO35MAkaN1PoghCNy4JGtqbp1e1wMkUifEwmAP9RIrStJdGj2YaHElQNwhiLDxjpmEh2COkQ1RnERiWpwfJXu0sW038/7lxL6RNQVXf9ZJxF02pbJKGpaL2gvPDQeLkdGMkArDR2Zuc1TIHVx/PrkCpehIm5nawMIzJ83Kug5p+TSnLG4Jx1Vzb9TW8paSn1hZacoV2sVhBvirDW6X6v0TbTyHLylpR1oHTwGdloxxBk3xezV0XpwyjIpFs0CZdsixcus=
      eksademo@eksa-admin

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: workload
  namespace: default
spec:
  cloneMode: fullClone
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/SDDC-Datacenter/vm/EKSAPOC-IND-TML
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/bottlerocket-v1.26.4-kubernetes-1-26-eks-10-amd64-a195374
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0DtKDP/zEo0PS9lURD8K/EXrblDji4lb/Dh6J6GEsLHs3eNTMp1NTA9+dPZIdUHv+UpFK9m3WdjWROgX81KDGsKktLwI1l9Q+01NsGFYSypsLE1T4YZWXMvWBqOIkRmG0dYCyr2DCQ7dexmJ0f7rXZt1EH9UgFelbevVxABXkixt1VAEN3IQGiPx8eXBFzjQRXQG5XoILUlLPNxmCzc1E5pNyAep50Onq5BNwqf0X1i9WPqeLy1ipOKUsO6SO35MAkaN1PoghCNy4JGtqbp1e1wMkUifEwmAP9RIrStJdGj2YaHElQNwhiLDxjpmEh2COkQ1RnERiWpwfJXu0sW038/7lxL6RNQVXf9ZJxF02pbJKGpaL2gvPDQeLkdGMkArDR2Zuc1TIHVx/PrkCpehIm5nawMIzJ83Kug5p+TSnLG4Jx1Vzb9TW8paSn1hZacoV2sVhBvirDW6X6v0TbTyHLylpR1oHTwGdloxxBk3xezV0XpwyjIpFs0CZdsixcus=
      eksademo@eksa-admin

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: my-github-flux-provider
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/eksa-poc
  github:
    owner: 22vibhutigoel
    personal: true
    repository: eksa
  systemNamespace: default

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: AWSIamConfig
metadata:
  name: aws-iam-auth-config
  namespace: default
spec:
  awsRegion: us-east-1
  backendMode:
  - EKSConfigMap
  mapRoles:
  - groups:
    - system:masters
    roleARN: arn:aws:iam::880926402103:role/custom-OIDC-eksa-forLogging
    username: eksa-role
  mapUsers:
  - groups:
    - system:masters
    userARN: arn:aws:iam::880926402103:user/eksa-test
    username: eksa-test
  partition: aws

---
